language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- npm run lint
deploy:
  provider: heroku
  app: angular-performance-test
  api_key:
    secure: fuOxwEFtLUsrR1wYI8oqtRoLlYYRsoTX08/stt6ftD5XfAvODkbG9DMFEWMpM9A/tUemRWQ2TUztFNn3A/S05g8nrjUgCHBdFsPQsYVJFK4zVf9DJH9TW2z+VbO5kHSDzq9NoZF4GgG04pR0Al3OiOl7gDVAZh2/znrP1U1qNkRObwBR5Hx+cNOid9i3YhrCsOLxyT3LC7e/9+ZBMcubpwX8asPUXS8qk7tMe3ghVqS8abULTjc/dicNOE0crq3Jn4I56GZSZteaHoyQ8a9RNSSMuFjBF3qFXrpygZuhDyscZZAdaVO+fKe7xcsRypqoQZAtE//sk2w4LqnEF0/QewGPdVgujCJ1/6e3jFXJdNmb/ShxlTKpBRN/3mzAqelD1C532LbZXIdo7NjLrvxBZah+XiQxrDtbxS0o/LuaWI/uQ2HmvtXC0vQEsq9Exf2iIjipZ2Dw/xkapJ/IWftma+pardQMhr42+MsUxUCzJFBnkWUWOYOFJZ3RAIcUu58iBiDgIg98TX4ZUX4Lu6Ky1L6l9Mfk4Bioyx7RiA6XeTePYgUZRCdvkn3+2JX7BVupmGqIf0I+TKww79MBtgGb89y11Q0od6fmBeGIXIEOF4zmHln8sN6X76bMBtnUWvJgEc7fVkDHk/KfnjJmUizkgphPrF0XbKHUmCWOf+YM/+A=
  on:
    repo: degreeproject/angular-performance-test
    branch: master
