language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- npm run lint
deploy:
  provider: heroku
  app: angular-performance-test
  api_key:
    secure: a3a3G/XWKk0qd6MvNmebuMPARsA7l88sqQ5YiSHGJcmwXoiMU+fJ+0jymwjfLtEbToBZHahIw+pKVVB3XSl2K6kezh+B5Hu+H/EpF10QBBg2gxA5xxilBd6v68FlLqDK8emStCkx6U7woH+pcOGeFY9oIP6I/1Yn1uj5jC0ZcUzUX1E8CFOuSVIvVeBP1Kz/dlAaRK/k0as4+GM5oZygwYMaEgt0KaHvDwcne79HZpB2FY/jTUNuIfq46cDuZtwZaRMLNXP6U/lT9/ObwunVUmWiG/0D41VTJo501MV9dl6J2JYOGz00RjpGnh5dbD88AwW9p2CK9cwqjAm6nRG30BUWCAZc3r1HdDdknFl9DMnOPiAaKKYKaHJCW8pIkZ6mdyQP2i3hyoOEUi6hB+ji2D2u/XJKlfN1M+o2aoh7XvgYyv4eR4PLSJtdJZpklnK20uM/qkZAVbLJ3Nk1A3lFM450cXa5olpT4jIZ1MfSMAPJA9SxlabKU/BgjB7LwA4+JRwNbSTYjJnnjmLmxbt7SvFQyQSEfo6mnup+0h9+Q/GwqG4P/2Ykcn5ssIL+ZflzrrskvNJ85au97qf0LxoMhbQDSuEBKA7QYQ1vVNj4xiTNyEgifxEiqO+9drlbSzQDAMJF+T17ra++SUsevEIAq9/Kc0pCEGg97d6AyentCIc=
  on:
    repo: degreeproject/angular-performance-test
    branch: master
