language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- npm run lint
deploy:
  provider: heroku
  app: angular-performance-test
  api_key:
    secure: Ir8dW/eFFqIfv4JFGmz2pErIar3OUZzh/LjVbrTZ/ThjGcCQUXrtbpDO5ms3+qC8ZcGSbV//sWqoEFVVjoR+Rvl391PvIu1bX1xIXHtbwHOnpahT/yM5TKroUfqniOzb9dpPfSzPSEWgfntTgP8bTyPo8v5Q8mZa9QA0FHgNuyhWAb2cWwjsGmwmegdnCdVgf0sWvaFNz6q7rTVOdU0EmZOrXR/cEGQGQFREbYbMdKds/FIGqXDHFT/AfUG//PAz0rH5j5RaCjNcxb4x9/XVxqdPR3vOuti1rMAqTpDikVLA4Xhcc+YlOKIwBvIiZoBxNk8gB7j9Qj4iYFxZ6vYCEUOu6FhXfjjVVbl21TxSMjL4oPAepBAMdQqmCKs3jpelsHgXjILJAmcr1/DCJYM3KkLtzOZU1ojbPuqHu/YpHkh/1bU00DptkRjwrEXJVBUovm0Id2pV2gkxazPe937UM3taoZFAtPBR6WPJRd66pvQzTNMdz9CfaLEqO0+UegJMoBs91b7C8XrhxzMQStdXff0Z0SMN+aIw3uXvQIvBLRfcvxWJLVNkyNXLZW/jKzocvbtgcH9s0DVukAeySHdSNzPbiMCPTsm/7XPSj12HyPwxn07TQyYoD/057+caxhf1yc18y0DI99PvUecuflmrMcKhuGjnPYxqAbN6HPLmOuA=
  on:
    repo: degreeproject/angular-performance-test
    branch: master
