language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- npm run lint
deploy:
  provider: heroku
  app: angular-performance-test
  api_key:
    secure: aHeuavJRtJO+MmofEg0Cpg+JqGB6lDV/H8ElKaFgSY8zsvuRVLOyB8qBQrajwI4JfS8+dbO8FJzziOAmiWTPy1JzYY8i2Ni5E5srlUqh1JxYAtUGV6X3K1p7QNkh0unHxbHqJr66xqS19epCQWuDel4alm7B8SBFJ3jCRu4+AcqC8vNpDRUW25tq9wns4iMgromvirD0bohyuL90jBLCcYFSikGiodm9lF75vFmYyi1OKPvzioY3ih/3Gw+M/1vnhipF5VvauRL/VWmoDJnFYE5iXstF1erlNu8eVdlLe8GFCB4B3bjw+w7xmxejhwyseb6IDNi7nVz7Q5qklQuMCcqJxKzVetFBwRP1XZJsM35MV1Mko5xuWnYf4xigHUmFXAQn2oU2GXJYbzB+hzkd19S1fyKzQoPBZlWpf6h4nSXWVgpUs6aEq6EkpuPJvEtaOuuKKkpa3H/V6LqVjNqzpvv9k0Ok1RX3AzvzIY08EbIAjPMgbQREnx0MIjLvfGNfsGvYSnzPwaJ9o9Sf10WMRwqGECjV929qBSeGcb2381GURl95FYVjKriBUk75gvw2lCZ0rkPfj9kAU2dZeBMoNrS90NmK1eYolR08G73X1LEY0CGQN0WIIrO8DFnI5VTHNsb2Fd+i4QU9JifC1W3hX/Myve/dH/NZ2au+UAwFDlo=
  on:
    repo: degreeproject/angular-performance-test
    branch: master
