language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- npm run lint
deploy:
  provider: heroku
  app: angular-performance-test
  api_key:
    secure: VPyQPwWtNgrr5z3Nf1jPFBdlat8gGEsuE9rnduZCUAAyOnEllBqw7yrHxVQLHNhl2CbP7ve21X4IdZy+4jD3adVS0CMOuxpNxwo9Tp4eWjevkov3+ygsSinIYW7mMcD3IXACa3aKQOYZ4S5f1CNZq+ZuDCq0RFCrG2TPTYH7RfgkhDBVho3ph5YzGJ0jJ/Yz75tmleTyKAywTN1xWIBKV19JFJgH9Qv9WwGL0h7EHI/2YHC3Ch1nH+hQRrEOyXpWzasDPizbi5lTpBXrGI/Q2q5IGhJ1kRpNb7d11GPjF6RAwXA0bgy0cgeWvjcO1ja3ISi9csOYqMR4UCTyOsQp8hSBYKtsfGPKTXBf80GojK13Df74snMXdd+UOIfw6p9T0s7x9l0EvqLcZ4wGMCkYbNyXxoVs+dJmtQDoCKIbbHPgd1uB/L2cmX8lC3CoCCsYGndUxZXAC9VReuJi80rvla4gDTl+CXQp/E+LAdnGpiBWPGk1DJRqT9P1f3T6g7o0xHQHDFZBQpnp8L2I8+kB3CUawLUojb0bfizpPxPCIP7ZRiBzhlsIYm6NWp3Un4HvRlQ000UbVIkJDOVecqKzK70/RcakD81UVyXROo9EysQ+nhmDkEOAcdLo6dJRQNMpG3fOZDpWT/SQ85MR0tafxlZlaKHYPgWh2uutNjqLO54=
  on:
    repo: degreeproject/angular-performance-test
    branch: master
