language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- npm run lint
deploy:
  provider: heroku
  app: angular-performance-test
  api_key:
    secure: JrXapJmMe4AhQ5P5trD5mknRcI/qN3Cdx0oFquS+3shNoEfO+uxXc5/czH8+ucsHH39Ch2XeFOqnYCe80icItVD5Ih76HCPNs9MIP8op/b7gtohGoGsMREamg0dr5w9EGrfrNBdSCT8cLxRFZ1mFxuChQnwnJ+7vwvtDthHV/2HTYCRCd5WqH9eBrPcAYKfuJghj63guKKGXlMjFx3hXRBf7OErLEf8t1LRvt1RdnzwGVW4D39sTFgnYu8QNcd6rn7kJYWkJmFZlPklVSIW3Jia7za6gQzl9E8V6/Hwnqok5SDdgerEmHYzlGWzLHg8tbq7CWRGZwQ1rpDMlHdL2xtrjxtXHeE7SqEQWeNPVf1DUCyz09u3lUjBelmLDNrNOOlNNr7HBJGWyz3ufxZ6EtAfMQUN0jW6uaXA7vn17jPVKcHnGMhNLyXkE7OrfEAa+5s/VCcnBP6E31CRyc12nVH9almPEnGiM+ATtLz19hRE8LhhpihyhRNBDh2qDUcdi6mSfkR89n2MEEFIeDVYKW0qxTK6F2sBO6Gc2BXaer3l9vzlki+dMjqk1gCBydShVfqrzASv1FNXyE4yGCb42+ug8cszGsAWiKLeIPEPCv6f+LYl6ZhaIBcHQrD5u3bDrCxJGciX6m2KBNvVPLydtrM6NbIQl8IVtZxz4g0/nLFY=
  on:
    repo: degreeproject/angular-performance-test
    branch: master
